<a href="https://colab.research.google.com/github/sepehrasadiyan/athletic_movement_detection/blob/pytorch/00_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.6.0+cu124


In [ ]:
# prompt: give me text of what is tensor and how we use it in pytorch

import numpy as np
# A tensor is a multi-dimensional array, similar to NumPy's ndarray,
# but with added features that make it suitable for deep learning.
# In PyTorch, tensors are used to represent the input data,
# model parameters, and outputs.

# Here's a simple example of how we can create and use tensors in PyTorch:

# Creating a tensor:
x = torch.tensor([1, 2, 3])
print(x)

# Performing operations on tensors:
y = x + 2
print(y)

# Converting a NumPy array to a tensor:
numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

# Converting a tensor to a NumPy array:
tensor_to_numpy = tensor_from_numpy.numpy()
tensor_to_numpy

# You can also create tensors of different data types, shapes, and sizes.
# These tensors can be used to build neural networks, perform calculations,
# and manipulate data in a way that's optimized for deep learning.

tensor_2d = torch.rand(2, 3)
tensor_2d



tensor([1, 2, 3])
tensor([3, 4, 5])
tensor([1, 2, 3])


array([1, 2, 3])

In [ ]:
# prompt: give me more future about it. like how DET work. or matrix multiplication. give me

# DET (Determinant)

# The determinant is a scalar value that can be computed from the elements of a square matrix.
# It provides information about the linear transformation represented by the matrix.
# In particular, it indicates whether the matrix is invertible (non-singular) or not.

# Example:
matrix = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
determinant = torch.linalg.det(matrix)
print(f"Determinant of the matrix: {determinant}")

# Matrix Multiplication

# Matrix multiplication is a fundamental operation in linear algebra and deep learning.
# It involves multiplying two matrices together to produce a new matrix.
# The resulting matrix's dimensions depend on the dimensions of the input matrices.

# Example:
matrix1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
matrix2 = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
product = torch.matmul(matrix1, matrix2)
print(f"Matrix multiplication result:\n{product}")


# More advanced concepts in PyTorch

# Automatic differentiation (Autograd):
# PyTorch uses automatic differentiation to calculate gradients of functions.
# This is crucial for training neural networks.
# You can specify which tensors require gradients using the requires_grad=True parameter.

# Example:
x = torch.tensor([1.0, 2.0], requires_grad=True)
y = x**2 + 2*x
#y.backward()  # Compute the gradients of y with respect to x
print(f"Gradient of y with respect to x: {x.grad}")

# Neural network building with PyTorch:
# PyTorch provides tools to build complex neural networks using layers, activation functions,
# optimizers, and loss functions.

# Example:
import torch.nn as nn

class MyNeuralNetwork(nn.Module):
  def __init__(self):
    super(MyNeuralNetwork, self).__init__()
    self.layer1 = nn.Linear(2, 5) # Input layer with 2 features, output layer with 5 neurons
    self.layer2 = nn.Linear(5, 1) # Output layer with 1 neuron
    self.relu = nn.ReLU()

  def forward(self, x):
    x = self.layer1(x)
    x = self.relu(x)
    x = self.layer2(x)
    return x

model = MyNeuralNetwork()

# You can then use this model to make predictions, train it on data, etc.


Determinant of the matrix: -2.0
Matrix multiplication result:
tensor([[19., 22.],
        [43., 50.]])
Gradient of y with respect to x: None
